export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightcoral", padding: "10px", textAlign: "center" }}>
          header
        </header>
        <main>{children}</main>
        <footer style={{ backgroundColor: "lightcoral", padding: "10px", textAlign: "center" }}>
          footer
        </footer>
      </body>
    </html>
  );
}
